### ISSUE TITLE
UI Error

### ISSUE THREAD

**Issue by irsdl** [The-Login/DNS-Analyzer#2]
Clicking on the column header to sort the table causes an error:
![image](https://github.com/The-Login/DNS-Analyzer/assets/1798313/f6c18506-e17b-47f2-bb97-3f0de5f37cc0)

Here is an error example:
```
java.lang.ClassCastException: class burp.api.montoya.collaborator.DnsQueryType cannot be cast to class java.lang.String (burp.api.montoya.collaborator.DnsQueryType is in unnamed module of loader 'app'; java.lang.String is in module java.base of loader 'bootstrap')
        at java.base/java.text.Collator.compare(Collator.java:305)
        at java.desktop/javax.swing.DefaultRowSorter.compare(DefaultRowSorter.java:981)
        at java.desktop/javax.swing.DefaultRowSorter$Row.compareTo(DefaultRowSorter.java:1391)
        at java.desktop/javax.swing.DefaultRowSorter$Row.compareTo(DefaultRowSorter.java:1381)
        at java.base/java.util.ComparableTimSort.countRunAndMakeAscending(ComparableTimSort.java:320)
        at java.base/java.util.ComparableTimSort.sort(ComparableTimSort.java:202)
        at java.base/java.util.Arrays.sort(Arrays.java:1041)
        at java.desktop/javax.swing.DefaultRowSorter.sort(DefaultRowSorter.java:616)
        at java.desktop/javax.swing.DefaultRowSorter.setSortKeys(DefaultRowSorter.java:315)
        at java.desktop/javax.swing.DefaultRowSorter.toggleSortOrder(DefaultRowSorter.java:476)
        at java.desktop/javax.swing.plaf.basic.BasicTableHeaderUI$MouseInputHandler.mouseClicked(BasicTableHeaderUI.java:130)
        at java.desktop/java.awt.AWTEventMulticaster.mouseClicked(AWTEventMulticaster.java:278)
        at java.desktop/java.awt.Component.processMouseEvent(Component.java:6623)
        at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3398)
        at java.desktop/java.awt.Component.processEvent(Component.java:6385)
        at java.desktop/java.awt.Container.processEvent(Container.java:2266)
        at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4995)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4827)
        at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
        at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4584)
        at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
        at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4827)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:775)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:747)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:744)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

Burp Suite Pro v2023.10.1-23046 on Windows

**Comment by The-Login** [comment]
Thanks for taking your time and reporting this issue!
It seems like there are some general problems when sorting some of the values (e.g., Collaborator ID, Query Type, etc.).
Since the extension was just officially released in the BApp store, I'll fix this bug (and probably many more) in the next version/release!
